server:
  port: 80
  servlet:
    session:
      tracking-modes: COOKIE

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${prd-db-url}
    username: ${prd-db-username}
    password: ${prd-db-password}
    transaction:
      rollback-on-commit-failure: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
